version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Africa/Johannesburg
  open-pull-requests-limit: 12
  target-branch: develop
  reviewers:
  - wax911
  labels:
  - dependencies
